version: '3'
services:
  database:
    container_name: database
    image: mongo:latest
    volumes:
      - /usr/local/database
    expose:
      - 27017
    restart: on-failure
  message-broker:
    container_name: message-broker
    image: eclipse-mosquitto:latest
    command: [ 'mosquitto', '-c', 'mosquitto-no-auth.conf' ]
    volumes:
      - /usr/local/message-broker
    expose:
      - 1883
    restart: on-failure
  simulator:
    container_name: simulator
    build: ./src/simulator
    volumes:
      - /usr/local/simulator
    depends_on:
      - message-broker
    links:
      - message-broker
    ports:
      - 1880:1880
    restart: on-failure
  pricing-service:
    container_name: pricing-service
    build: ./src/services/pricing
    volumes:
      - /usr/local/pricing-service
    depends_on:
      - database
    links:
      - database
    ports:
      - 1005:1005
    restart: on-failure
  vehicles-service:
    container_name: vehicles-service
    build: ./src/services/vehicles
    volumes:
      - /usr/local/vehicles-service
    depends_on:
      - database
      - pricing-service
    links:
      - database
      - pricing-service
    ports:
      - 1004:1004
    restart: on-failure
